//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Acceso
    {
        public int Id { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
        public Nullable<int> Id_Submenu { get; set; }
    
        public virtual LineaNegocio LineaNegocio { get; set; }
        public virtual Submenu Submenu { get; set; }
    }
}
