//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AjusNcRealVsDevROM
    {
        public long Id { get; set; }
        public string PLMN { get; set; }
        public Nullable<int> OPERADOR { get; set; }
        public string DEUDOR { get; set; }
        public Nullable<decimal> ProvisionTarifaMesAnterior { get; set; }
        public Nullable<decimal> ProvisionTarifaReal { get; set; }
        public Nullable<decimal> Ajustes_tarifa { get; set; }
    }
}
