//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelacionProvROM
    {
        public long Id { get; set; }
        public Nullable<int> No_PROVISION { get; set; }
        public Nullable<int> DEUDOR { get; set; }
        public Nullable<int> Sociedad_GL { get; set; }
        public string ID_OPERADOR { get; set; }
        public string TIPO_O_CONCEPTO { get; set; }
        public Nullable<System.DateTime> PERIODO { get; set; }
        public string MONEDA { get; set; }
        public Nullable<decimal> IMPORTE_MD { get; set; }
        public Nullable<decimal> IMPORTE_MXN { get; set; }
        public Nullable<decimal> TC { get; set; }
        public string FOLIO_DOCUMENTO { get; set; }
        public Nullable<int> No_DOC_SAP { get; set; }
        public string GRUPO { get; set; }
    }
}
