//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelacionProvisionesCosto
    {
        public int Id { get; set; }
        public string BanderaConcepto { get; set; }
        public Nullable<decimal> NoProvision { get; set; }
        public string IdOperador { get; set; }
        public string Concepto { get; set; }
        public string Grupo { get; set; }
        public Nullable<decimal> Acreedor { get; set; }
        public Nullable<decimal> MontoProvision { get; set; }
        public string Moneda { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public string Tipo { get; set; }
        public Nullable<decimal> NoDocumentoSap { get; set; }
        public string FolioDocumento { get; set; }
        public Nullable<decimal> TcProvision { get; set; }
        public Nullable<decimal> ImporteMxn { get; set; }
        public Nullable<decimal> ImporteFactura { get; set; }
        public Nullable<decimal> DiferenciaProvVsFactura { get; set; }
        public Nullable<decimal> TipoDeCambioFactura { get; set; }
        public Nullable<decimal> ExcesoProvisonMxn { get; set; }
        public Nullable<decimal> InsuficienciaProvisionMxn { get; set; }
    }
}
