//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CancelacionCostoRom
    {
        public int Id { get; set; }
        public string Bandera { get; set; }
        public int No_Provision { get; set; }
        public int Id_Operador { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> Id_Grupo { get; set; }
        public int Id_Acreedor { get; set; }
        public Nullable<int> Monto_Provision { get; set; }
        public Nullable<int> Id_Moneda { get; set; }
        public System.DateTime Periodo { get; set; }
        public string Tipo { get; set; }
        public int No_Documento_Sap { get; set; }
        public string Folio_Documento { get; set; }
        public Nullable<decimal> TC_Provision { get; set; }
        public decimal Importe_MXN { get; set; }
        public Nullable<decimal> Importe_Factura { get; set; }
        public Nullable<decimal> Diferencia_ProvFactura { get; set; }
        public decimal Tipo_Cambio_Factura { get; set; }
        public decimal Exceso_Provision_MXN { get; set; }
        public Nullable<decimal> Insuficiencia_ProvisionMXN { get; set; }
        public int Activo { get; set; }
        public int Id_LineaNegocio { get; set; }
    }
}
