//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CaracteristicasPA
    {
        public int Id { get; set; }
        public string Sentido { get; set; }
        public string CodigoMaterial { get; set; }
        public string DescripcionMaterial { get; set; }
        public string Cuenta { get; set; }
        public string SubsegmentoPA { get; set; }
        public string SegmentoPA { get; set; }
        public string Producto { get; set; }
        public string Canal { get; set; }
        public string Bundle { get; set; }
        public Nullable<int> Trafico_Id { get; set; }
        public string TraficoDescripcion { get; set; }
        public string Subtipolinea { get; set; }
        public string Nlicencia { get; set; }
        public string Region { get; set; }
        public string Ambito { get; set; }
        public Nullable<int> idCuenta { get; set; }
        public int Activo { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
    
        public virtual CuentaResultado CuentaResultado { get; set; }
        public virtual Trafico Trafico { get; set; }
    }
}
