//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CargaDocumento
    {
        public int Id { get; set; }
        public string Id_Documento { get; set; }
        public string Periodo { get; set; }
        public Nullable<System.DateTime> FechaCarga { get; set; }
        public string EstatusCarga { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
    }
}
