//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CosRomCieFacturacionCostosRecurrentes
    {
        public int CosRomCieFacturacionCostosRecurrentesId { get; set; }
        public Nullable<System.DateTime> FechaFactura { get; set; }
        public Nullable<System.DateTime> FechaConsumo { get; set; }
        public string Concepto { get; set; }
        public Nullable<int> OperadorId { get; set; }
        public string NoConfirmacionSap { get; set; }
        public Nullable<int> MonedaId { get; set; }
        public Nullable<decimal> Facturado { get; set; }
        public string Grupo { get; set; }
        public Nullable<decimal> Tc { get; set; }
        public Nullable<decimal> Mxn { get; set; }
        public string Tipo { get; set; }
    }
}
