//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CosRomCieTC
    {
        public long CosRomCieTCId { get; set; }
        public System.DateTime Periodo { get; set; }
        public int MonedaId { get; set; }
        public string Concepto { get; set; }
        public string Tipo { get; set; }
        public decimal Tc { get; set; }
    }
}
