//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CosRomCieProvTar
    {
        public int CosRomCieProvTarId { get; set; }
        public Nullable<int> OperadorId { get; set; }
        public Nullable<int> PXQCostosROMId { get; set; }
        public Nullable<int> CostoMovimientoPeriodosAnterioresId { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<decimal> ProvTarifa { get; set; }
        public Nullable<decimal> AjusteTarifaRealVsProvisionMesPasado { get; set; }
        public Nullable<decimal> ProvisionTarifaDevengada { get; set; }
        public Nullable<decimal> ProvisionNcTarifaCancelada { get; set; }
        public Nullable<decimal> ProvisionDeCostoCancelada { get; set; }
        public Nullable<decimal> ProvisionNcTarifa { get; set; }
        public Nullable<decimal> ProvisionDeCostoTarifaCancelada { get; set; }
        public Nullable<decimal> TotalProvisionNcTarifa { get; set; }
        public Nullable<decimal> TotalProvCostoTarifa { get; set; }
        public Nullable<decimal> ComplementoTarifaMesesAnteriores { get; set; }
        public Nullable<decimal> TotalProvTarifa { get; set; }
    }
}
