//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CosRomCieCostosRecurrentes
    {
        public int CosRomCieCostosRecurrentesId { get; set; }
        public Nullable<int> OperadorId { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<int> ModedaId { get; set; }
        public Nullable<decimal> RemanenteProvCostoRecurrente { get; set; }
        public Nullable<decimal> RemanenteTotalProvCostoRecurrente { get; set; }
        public Nullable<decimal> RealConfirmadoProvCostoRecurrente { get; set; }
        public Nullable<decimal> RealConfirmadoTotalProvCosto { get; set; }
        public Nullable<decimal> CancelacionProvCostoRecurrente { get; set; }
        public Nullable<decimal> CancelacionTotalProvCostoRecurrente { get; set; }
        public Nullable<decimal> RemantenteActualCostoRecurrente { get; set; }
        public Nullable<decimal> TotalCostoRecurrente { get; set; }
        public Nullable<decimal> TCPromedio { get; set; }
    }
}
