//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CosRomCieCosto
    {
        public Nullable<System.DateTime> Periodo { get; set; }
        public int CosRomCieCostoId { get; set; }
        public string CuentaDeResultados { get; set; }
        public Nullable<int> OperadorId { get; set; }
        public Nullable<int> MonedaId { get; set; }
        public Nullable<decimal> CancelacionDevengoTrafico_CostosRecurrentesMesAnterior { get; set; }
        public Nullable<decimal> CancelacionProvNcTarifaMesAnterior { get; set; }
        public Nullable<decimal> CancelacionProvCostoTarifaMesAnterior { get; set; }
        public Nullable<decimal> CancelacionDevengoTotalMesAnterior { get; set; }
        public Nullable<decimal> FacturacionTrafico_CostoRecurrente { get; set; }
        public Nullable<decimal> FacturacionTarifa { get; set; }
        public Nullable<decimal> NcrTrafico { get; set; }
        public Nullable<decimal> NcrTarifa { get; set; }
        public Nullable<decimal> DevengoCostoTrafico_CostoRecurrente { get; set; }
        public Nullable<decimal> ProvCostoDifTarifa { get; set; }
        public Nullable<decimal> ProvNcDifTarifa { get; set; }
        public Nullable<decimal> ExcesoOInsufDevMesAnt { get; set; }
        public Nullable<decimal> OtrosAjustes { get; set; }
        public Nullable<decimal> FluctuacionAReclasificar { get; set; }
        public Nullable<decimal> TotalDevengo { get; set; }
        public Nullable<bool> EsCostoRecurrente { get; set; }
    }
}
