//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CosRomCieProvTarAcumMesesAnte
    {
        public int CosRomCieProvTarAcumMesesAnteId { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<System.DateTime> PeriodoCalculo { get; set; }
        public Nullable<decimal> ProvNcTarifaUsd { get; set; }
        public Nullable<decimal> ProvCostoTarifaUsd { get; set; }
        public Nullable<decimal> ProvTarifaTotalUsd { get; set; }
        public Nullable<decimal> CancelacionProvisionNcTarifa { get; set; }
        public Nullable<decimal> CancelacionProvisionCostoTarifa { get; set; }
        public Nullable<decimal> TotalNcAcumuladaPeriodosAnteriores { get; set; }
        public Nullable<decimal> TotalProvCostoAcumuladaPeriodosAnteriores { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<decimal> ProvNcTarifaMxn { get; set; }
        public Nullable<decimal> ProvCostoTarifaMxn { get; set; }
    }
}
