//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CostoFR
    {
        public int Id { get; set; }
        public string TipoOperador { get; set; }
        public string Operador { get; set; }
        public string AcreedorSap { get; set; }
        public string NombreProveedor { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public string Fecha_Inicio { get; set; }
        public string Fecha_Fin { get; set; }
        public string CuentaR { get; set; }
        public Nullable<int> SociedadGL { get; set; }
        public Nullable<decimal> TC { get; set; }
        public int Activo { get; set; }
        public int Id_LineaNegocio { get; set; }
    }
}
