//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CuentaResultado
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CuentaResultado()
        {
            this.CaracteristicasPA = new HashSet<CaracteristicasPA>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Trafico_Id { get; set; }
        public string TraficoDescripcion { get; set; }
        public string Sentido { get; set; }
        public string Cuenta { get; set; }
        public string Codigo_Material { get; set; }
        public string Material { get; set; }
        public int Activo { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CaracteristicasPA> CaracteristicasPA { get; set; }
        public virtual Trafico Trafico { get; set; }
    }
}
