//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevAcumTraficoIngresoROM
    {
        public long Id { get; set; }
        public string PLMN { get; set; }
        public string OPERADOR { get; set; }
        public Nullable<int> DEUDOR { get; set; }
        public Nullable<decimal> DevengoTrafico_MESCIERRE { get; set; }
        public Nullable<decimal> DevengoPendEmitirFechaProvisionIngresoPendienteEmitir { get; set; }
        public Nullable<decimal> DevengoAcumuladoFechaCierre { get; set; }
        public Nullable<decimal> DevengoAcumuladoA30_11_2018 { get; set; }
    }
}
