//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevengoFluctuacionROM
    {
        public int Id { get; set; }
        public Nullable<int> Cuenta_Contable { get; set; }
        public string Deudor_SAP { get; set; }
        public string PLMN { get; set; }
        public string Periodo { get; set; }
        public string Tipo_Registro { get; set; }
        public string Moneda { get; set; }
        public Nullable<decimal> TC_Provision { get; set; }
        public Nullable<decimal> Provision { get; set; }
        public Nullable<decimal> Importe_MXN { get; set; }
        public Nullable<decimal> TC_Facturado { get; set; }
        public Nullable<decimal> Importe_Facturado { get; set; }
        public Nullable<decimal> Importe_Facturado_MXN { get; set; }
        public Nullable<decimal> Variacion_Real_Provicion { get; set; }
        public Nullable<decimal> Variacion_MXN { get; set; }
        public Nullable<decimal> Efecto_Negocio { get; set; }
        public Nullable<decimal> Provicion_Soportada { get; set; }
        public Nullable<decimal> Efecto_Opertivo_Finanzas { get; set; }
        public Nullable<decimal> Fluctuacion_Cambiaria { get; set; }
        public Nullable<decimal> Efecto_Negocio_Neto { get; set; }
    }
}
