//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DevengoAcumTraficoIng
    {
        public int Id { get; set; }
        public string PLMN { get; set; }
        public string Operador { get; set; }
        public string deudor { get; set; }
        public Nullable<decimal> devengoTrafico { get; set; }
        public Nullable<decimal> devengoPendEmitir { get; set; }
        public Nullable<decimal> devengoAcumulado { get; set; }
    }
}
