//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FacturaTarifaROM
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> FECHAINICIO { get; set; }
        public Nullable<System.DateTime> FECHAFIN { get; set; }
        public string PLMN { get; set; }
        public Nullable<int> DEUDOR { get; set; }
        public string OPERADOR { get; set; }
        public string FOLIOFACTURASAP { get; set; }
        public Nullable<decimal> FACTURADOSINIMPUESTOS { get; set; }
        public string GRUPO { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<decimal> MXN { get; set; }
    }
}
