//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FluctuacionIngresoROM
    {
        public int id { get; set; }
        public int no_Provision { get; set; }
        public int cuenta_Contable { get; set; }
        public string pmln { get; set; }
        public string nombre { get; set; }
        public int deudor { get; set; }
        public int sociedad_GL { get; set; }
        public System.DateTime periodo { get; set; }
        public string tipo { get; set; }
        public string tipo_Registro { get; set; }
        public string documento { get; set; }
        public int no_DocumentoSap { get; set; }
        public string moneda { get; set; }
        public decimal tC_Provision { get; set; }
        public decimal tC_Cierre { get; set; }
        public decimal tC_Facturado { get; set; }
        public decimal importe_Provision { get; set; }
        public decimal importe_ProvisionMXN { get; set; }
        public decimal importe_Revaluado { get; set; }
        public decimal importe_Facturado { get; set; }
        public decimal importe_Facturado_Provision { get; set; }
        public decimal facturado_MXN { get; set; }
        public decimal variacion_MXN { get; set; }
        public decimal efecto_Operativo { get; set; }
        public decimal fluctuacion_Cambiaria { get; set; }
        public string estatus { get; set; }
        public int cuenta_Fluctuacion { get; set; }
    }
}
