//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GADataCostoLDI
    {
        public int id { get; set; }
        public Nullable<System.DateTime> fecha_proceso { get; set; }
        public Nullable<System.DateTime> fecha_contable { get; set; }
        public Nullable<System.DateTime> mes { get; set; }
        public Nullable<int> id_movimiento { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<int> id_operador { get; set; }
        public Nullable<int> id_acreedor { get; set; }
        public Nullable<int> id_trafico { get; set; }
        public Nullable<decimal> segundos { get; set; }
        public Nullable<decimal> min_fact { get; set; }
        public Nullable<decimal> tarifa_ext { get; set; }
        public Nullable<decimal> tarifa_final { get; set; }
        public Nullable<decimal> cantidad { get; set; }
        public Nullable<decimal> importe_costo { get; set; }
        public string no_factura_referencia { get; set; }
        public Nullable<decimal> monto_facturado { get; set; }
        public Nullable<int> llamadas { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<decimal> sobrecargo { get; set; }
        public Nullable<int> estatus { get; set; }
        public Nullable<int> id_origen { get; set; }
    }
}
