//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaArchivo2
    {
        public int IdLinea2 { get; set; }
        public Nullable<int> Id_Devengo { get; set; }
        public string REG { get; set; }
        public string ClaveContab { get; set; }
        public string CME { get; set; }
        public string ImporteMD { get; set; }
        public string ImporteML { get; set; }
        public string IndicadorImpuesto { get; set; }
        public string CentroCosto { get; set; }
        public string Orden { get; set; }
        public string FechaBase { get; set; }
        public string Asignacion { get; set; }
        public string TextoPosicion { get; set; }
        public string CondPago { get; set; }
        public string BloqPago { get; set; }
        public string ViaPago { get; set; }
        public string BcoPropio { get; set; }
        public string Cuenta { get; set; }
        public string REF1 { get; set; }
        public string REF2 { get; set; }
        public string lineaDeNegocio { get; set; }
        public string Campo20 { get; set; }
        public string Campo21 { get; set; }
        public string Campo22 { get; set; }
        public string SociedadCuentasDeIngresos { get; set; }
        public string Subsegm { get; set; }
        public string Servicio { get; set; }
        public string Region { get; set; }
        public string Licencia { get; set; }
        public string TipoDeTrafico { get; set; }
        public string Ambito { get; set; }
        public string Producto { get; set; }
        public string Geografia { get; set; }
        public string Paquetes { get; set; }
        public string PlanRegulatorio { get; set; }
        public string EmpresaGrupo { get; set; }
        public string REF3 { get; set; }
        public string AreaFuncional { get; set; }
        public string CalculoImpuesto { get; set; }
        public string FechaValor { get; set; }
        public string IndicadorActividadPEl { get; set; }
        public string RegionEstadoFederalLandProvinciaCondado { get; set; }
        public string ClaseDeDistribuciónIRPF { get; set; }
        public string Campo42 { get; set; }
        public string Proyecto { get; set; }
        public string SociedadGLAsociada { get; set; }
        public string Campo45 { get; set; }
        public string CodMaterial { get; set; }
        public string CodEmplazFiscal { get; set; }
        public string Grafo { get; set; }
        public string Grafo2 { get; set; }
        public string Subsegmento { get; set; }
        public string BundlePaquetes { get; set; }
        public string SubtipoLinea { get; set; }
        public string Canal { get; set; }
        public string ServiciosPA { get; set; }
        public string SegmentoPA { get; set; }
        public string importebaseimpuesto { get; set; }
        public string ASIENTO { get; set; }
        public string Sentido { get; set; }
    }
}
