//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LineaArchivo1
    {
        public int IdLinea1 { get; set; }
        public Nullable<int> Id_Devengo { get; set; }
        public string Reg { get; set; }
        public string Trans { get; set; }
        public string ClaseDocumento { get; set; }
        public string Sociedad { get; set; }
        public string Moneda { get; set; }
        public string TipoCambio { get; set; }
        public string FechaDocumento { get; set; }
        public string FechaContabilizacion { get; set; }
        public string FechaReversion { get; set; }
        public string TextoCabecera { get; set; }
        public string MotivoReversion { get; set; }
        public string Libro { get; set; }
        public string Referencia { get; set; }
        public string Referencia2 { get; set; }
        public string IdCasuistica { get; set; }
        public string Asiento { get; set; }
        public string Referencia22 { get; set; }
        public string CalculoAut { get; set; }
        public string Sentido { get; set; }
    }
}
