//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LogActualizaciones
    {
        public int Id { get; set; }
        public string NombrePantalla { get; set; }
        public string ColumnaModificada { get; set; }
        public string Valor_Nuevo { get; set; }
        public string Valor_Anterior { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Direccion_IP { get; set; }
        public string Accion { get; set; }
        public string Usuario { get; set; }
        public int Activo { get; set; }
    }
}
