//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCTraficoROM
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> FECHA_TRAFICO { get; set; }
        public string PLMN { get; set; }
        public string DEUDOR { get; set; }
        public string OPERADOR { get; set; }
        public string FOLIOFACTURA_SAP { get; set; }
        public string FACTURADO_SIN_IMPUESTOS { get; set; }
        public string GRUPO { get; set; }
        public Nullable<decimal> TC { get; set; }
        public Nullable<decimal> MXN { get; set; }
    }
}
