//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotaCredito
    {
        public int id { get; set; }
        public string sentido { get; set; }
        public Nullable<int> id_sociedad { get; set; }
        public Nullable<int> id_trafico { get; set; }
        public Nullable<int> id_servicio { get; set; }
        public string deudorAcreedor { get; set; }
        public Nullable<int> id_operador { get; set; }
        public Nullable<int> id_grupo { get; set; }
        public Nullable<decimal> importe { get; set; }
        public Nullable<int> id_moneda { get; set; }
        public System.DateTime mes_consumo { get; set; }
        public Nullable<int> activo { get; set; }
        public Nullable<int> id_lineaNegocio { get; set; }
        public System.DateTime periodo_carga { get; set; }
    }
}
