//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Objecion
    {
        public int id { get; set; }
        public string Sentido { get; set; }
        public Nullable<int> Id_trafico { get; set; }
        public Nullable<int> Id_servicio { get; set; }
        public Nullable<int> Id_Sociedad { get; set; }
        public string Deudor_Acreedor { get; set; }
        public Nullable<int> Id_Grupo { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
        public Nullable<int> Id_operador { get; set; }
    
        public virtual Grupo Grupo { get; set; }
        public virtual Servicio Servicio { get; set; }
        public virtual Sociedad Sociedad { get; set; }
        public virtual Trafico Trafico { get; set; }
    }
}
