//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operador
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operador()
        {
            this.Acuerdo_Grupo = new HashSet<Acuerdo_Grupo>();
            this.BonoConsumo = new HashSet<BonoConsumo>();
            this.BonoTrafico = new HashSet<BonoTrafico>();
            this.Concepto = new HashSet<Concepto>();
            this.Movimiento = new HashSet<Movimiento>();
            this.Tarifa = new HashSet<Tarifa>();
            this.TarifaRoaming = new HashSet<TarifaRoaming>();
        }
    
        public int Id { get; set; }
        public string Id_Operador { get; set; }
        public string Nombre { get; set; }
        public string Razon_Social { get; set; }
        public Nullable<int> Id_Grupo { get; set; }
        public Nullable<int> Id_Deudor { get; set; }
        public Nullable<int> Id_Acreedor { get; set; }
        public Nullable<int> Id_Sociedad { get; set; }
        public string RFC { get; set; }
        public string Sociedad_GL { get; set; }
        public string Tipo_Operador { get; set; }
        public int Activo { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acuerdo_Grupo> Acuerdo_Grupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonoConsumo> BonoConsumo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BonoTrafico> BonoTrafico { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Concepto> Concepto { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Movimiento> Movimiento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarifa> Tarifa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TarifaRoaming> TarifaRoaming { get; set; }
    }
}
