//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class parametrosCargaDocumento
    {
        public int Id { get; set; }
        public string idDocumento { get; set; }
        public string servicio { get; set; }
        public string nombreDocumento { get; set; }
        public string nombreArchivo { get; set; }
        public string pathURL { get; set; }
        public Nullable<int> diaCorte { get; set; }
        public Nullable<int> horaCorte { get; set; }
        public string caracterSeparador { get; set; }
        public string caracterFinLinea { get; set; }
        public int activo { get; set; }
    }
}
