//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PeriodosAnterioresROM
    {
        public long IdRegistro { get; set; }
        public string BanderaConcepto { get; set; }
        public string Tipo { get; set; }
        public Nullable<int> IdOperador { get; set; }
        public string IdAcreedor { get; set; }
        public Nullable<System.DateTime> Periodo { get; set; }
        public Nullable<decimal> Importe { get; set; }
        public Nullable<int> IdMoneda { get; set; }
        public string Concepto { get; set; }
        public string FolioDocumento { get; set; }
        public Nullable<decimal> TipoCambio { get; set; }
        public Nullable<decimal> ImporteMXN { get; set; }
        public Nullable<int> IdGrupo { get; set; }
        public long Identificador { get; set; }
    }
}
