//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProvTarAcumMesesAnteROM
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> PERIODO { get; set; }
        public Nullable<decimal> ProvNcTarifaUSD { get; set; }
        public Nullable<decimal> ProvIngresoTarifaUSD { get; set; }
        public Nullable<decimal> ProvTarifaTotalUSD { get; set; }
        public Nullable<decimal> CancelacionProvisionNcTarifa { get; set; }
        public Nullable<decimal> CancelacionProvisionIngresoTarifa { get; set; }
        public Nullable<decimal> TotalNcTarifaAcumuladaActual { get; set; }
        public Nullable<decimal> TotalProvIngresoTarifaAcumuladaActual { get; set; }
        public Nullable<int> TC { get; set; }
        public Nullable<decimal> ProvNcTarifaMXN { get; set; }
        public Nullable<decimal> ProvIngresoTarifaMXN { get; set; }
    }
}
