//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROVTARIFA_MesAnteriorROM
    {
        public long Id { get; set; }
        public string PLMN { get; set; }
        public string OPERADOR { get; set; }
        public Nullable<int> DEUDOR { get; set; }
        public Nullable<decimal> PROVTARIFA_MesAnterior { get; set; }
        public Nullable<decimal> AjNcRealVsDevengMesAnter { get; set; }
        public Nullable<decimal> ProvDevengoTarifa_MesAnterior { get; set; }
        public Nullable<decimal> ProvisionNcTarifaCancelada { get; set; }
        public Nullable<decimal> ProvisionNcTarifa_MesAnterior { get; set; }
        public Nullable<decimal> TotalProvisionNcTarifa_MesAnterior { get; set; }
        public Nullable<decimal> ProvisionIngresoTarifaCancelada { get; set; }
        public Nullable<decimal> ProvIngresoTarifa_MesAnterior { get; set; }
        public Nullable<decimal> TotalProvIngresoTarifa_MesAnterior { get; set; }
        public Nullable<decimal> ComplementoTarifaMesesAnteriores { get; set; }
        public Nullable<decimal> TotalProvTarifa_MesAnterior { get; set; }
    }
}
