//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoamingDocumentoCosto
    {
        public int IdDocumentoCosto { get; set; }
        public string Anio { get; set; }
        public string FechaContable { get; set; }
        public string FechaConsumo { get; set; }
        public string Compania { get; set; }
        public string Servicio { get; set; }
        public string Grupo { get; set; }
        public string IdOperador { get; set; }
        public string NombreOperador { get; set; }
        public string Acreedor { get; set; }
        public string Material { get; set; }
        public string Trafico { get; set; }
        public string Iva { get; set; }
        public string PorcentajeIva { get; set; }
        public string Moneda { get; set; }
        public string Minutos { get; set; }
        public string Tarifa { get; set; }
        public string Monto { get; set; }
        public string MontoFacturado { get; set; }
        public string FechaFactura { get; set; }
        public string FolioDocumento { get; set; }
        public string TipoCambio { get; set; }
        public string MontoMxn { get; set; }
        public string CuentaContable { get; set; }
        public string ClaseDocumento { get; set; }
        public string ClaseDocumentoSap { get; set; }
        public string NumeroDocumentoSap { get; set; }
        public string Activo { get; set; }
        public string LineaNegocio { get; set; }
        public System.DateTime FechaCarga { get; set; }
    }
}
