//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sociedad
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sociedad()
        {
            this.Objecion = new HashSet<Objecion>();
            this.Tarifa_Fee = new HashSet<Tarifa_Fee>();
        }
    
        public int Id { get; set; }
        public string Id_Sociedad { get; set; }
        public string AbreviaturaSociedad { get; set; }
        public string NombreSociedad { get; set; }
        public string Id_SAP { get; set; }
        public string Sociedad_SAP { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Objecion> Objecion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tarifa_Fee> Tarifa_Fee { get; set; }
    }
}
