//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Submenu
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Submenu()
        {
            this.Acceso = new HashSet<Acceso>();
        }
    
        public int Id { get; set; }
        public Nullable<int> Id_Menu { get; set; }
        public string Nombre { get; set; }
        public string Controlador { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<int> carga { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Acceso> Acceso { get; set; }
        public virtual Menu Menu { get; set; }
    }
}
