//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IC2.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TarifaRoaming
    {
        public int Id { get; set; }
        public string Sentido { get; set; }
        public string Direccion { get; set; }
        public Nullable<int> Code { get; set; }
        public Nullable<int> Id_Operador { get; set; }
        public Nullable<System.DateTime> FechaInicio { get; set; }
        public Nullable<System.DateTime> FechaFin { get; set; }
        public Nullable<decimal> ToData { get; set; }
        public Nullable<decimal> ToSMSMo { get; set; }
        public Nullable<decimal> ToVoiceMo { get; set; }
        public Nullable<decimal> ToVoiceMt { get; set; }
        public Nullable<decimal> TfData { get; set; }
        public Nullable<decimal> TfSMSMo { get; set; }
        public Nullable<decimal> TfVoiceMo { get; set; }
        public Nullable<decimal> TfVoiceMt { get; set; }
        public Nullable<decimal> iva { get; set; }
        public Nullable<int> Activo { get; set; }
        public Nullable<int> Id_LineaNegocio { get; set; }
        public string Tipo { get; set; }
    
        public virtual Operador Operador { get; set; }
    }
}
